summary: Write DNF module configuration.
description: |-
  This stage allows writing DNF module configurations. These files are
  which are used by DNF to determine enabled modules.
schema_2:
  options:
    additionalProperties: false
    description: DNF configuration.
    properties:
      conf:
        additionalProperties: false
        type: object
        description: DNF module configuration values.
        properties:
          name:
            type: string
          stream:
            type: string
          state:
            type: string
          profiles:
            type: array
            items:
              type: string
