summary: Write bootc-install-config(5) file
description: |-
  The bootc install process supports some basic customization. This
  configuration file is in TOML format, and will be discovered by the
  installation process via drop-in files in `/usr/lib/bootc/install` that
  are processed in alphanumerical order.
  The individual files are merged into a single final installation config, so
  it is supported for e.g. a container base image to provide a default root
  filesystem type, that can be overridden in a derived container image.
schema:
  additionalProperties: false
  required:
  - filename
  - config
  properties:
    filename:
      type: string
      description: name of the configuration file.
    config:
      additionalProperties: false
      type: object
      minProperties: 1
      properties:
        install:
          type: object
          additionalProperties: false
          minProperties: 1
          properties:
            filesystem:
              type: object
              required:
              - root
              additionalProperties: false
              properties:
                root:
                  type: object
                  required:
                  - type
                  additionalProperties: false
                  properties:
                    type:
                      type: string
            kargs:
              type: array
              description: Append extra kernel arguments
              items:
                type: string
            block:
              type: array
              description: An array of supported to-disk backends enabled by this
                base container image; if not specified, this will just be direct.
              items:
                type: string
                enum:
                - direct
                - tmp2-luks
