name: Generate

on: [pull_request, push]

jobs:
  generate_documentation:
    name: "Documentation"
    runs-on: ubuntu-24.04
    container:
      image: docker.io/library/python:3.7
    steps:
      - name: Install Dependencies
        run: |
          pip install docutils

      - name: Clone repository
        uses: actions/checkout@v4
        with:
          path: osbuild

      - name: Generate Documentation
        run: |
          make \
            -f osbuild/Makefile \
            SRCDIR=osbuild \
            BUILDDIR=build \
            RST2MAN=rst2man.py \
            man

      - name: Verify Documentation
        working-directory: build
        run: |
          test -d docs
          test -f docs/osbuild.1

  generate_test_data:
    name: "Test Data"
    runs-on: ubuntu-24.04
    env:
      OSBUILD_MPP_CACHEDIR: "/var/tmp/osbuild-mpp-cache"
    steps:
    - name: "Clone Repository"
      uses: actions/checkout@v4
    - name: Cache metadata
      uses: actions/cache@v4
      with:
        path: /var/tmp/osbuild-mpp-cache
        key: no-key-needed-here
    - name: "Regenerate Test Data"
      uses: osbuild/containers/src/actions/privdocker@552e30cf1b4ed19c6ddaa57f96c342b3dff4227b
      with:
        image: ghcr.io/osbuild/osbuild-ci:latest-202512170944
        run: |
          make test-data
          git diff --exit-code -- ./test/data
